### ISSUE TITLE
When resuming the model training, errors occur

### ISSUE THREAD

**Issue by JM-IP** [larq/larq#174]
### Describe the bug
When running line 40 in .../larq_zoo/train.py model.load_weights(model_path),
Errors occur as : TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int8 of argument 'x'.

### To Reproduce
lqz train model_name --data=imagenet2012 --output-dir=...

### Environment

TensorFlow version: 
2.0.0b1
Larq version: 
0.5

**Comment by lgeiger** [comment]
It looks like Larq Zoo tries to reload an incompatible checkpoint. We included some fixes in [Larq version 0.6.0](https://github.com/larq/larq/releases) related to reloading of metrics (which are the only thing currently in `int8`).

Could you try again with Larq version 0.6.0 and Larq Zoo version 0.3.0. from an empty output directory, train for a few epochs and then try to resume?

If the error still shows up when resuming, it would be good if you could post the entire traceback and also try with TensorFlow version 1.14.0 to make sure we are not hitting a TensorFlow bug.

**Comment by appleleaves** [comment]
This solved the problems!
Thanks!

**Comment by lgeiger** [comment]
:+1: glad that resolved the problem

**Comment by appleleaves** [comment]
Using the imagenet2012 version 2.0.1, the resume training works fine.
However, using the updated larq@0.6.0, training occur error with "Not a JPEG file: starts with 0x89 0x50"


more information is shown below:
Train on 10009 steps, validate on 390 steps
Epoch 1/100
2019-08-08 11:35:53.623943: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-08 11:35:58.985567: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-08 11:36:04.151683: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
2019-08-08 11:36:04.153391: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.0
2019-08-08 11:36:05.407704: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 2581 kernel records, 85 memcpy records.
W0808 11:36:05.472160 140434071774976 callbacks.py:242] Method (on_train_batch_end) is slow compared to the batch update (0.613347). Check your callbacks.
Not a JPEG file: starts with 0x89 0x50
Traceback (most recent call last):
  File "/home/yjm/anaconda2/envs/yjm_py3/bin/lqz", line 11, in <module>
    sys.exit(cli())
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/zookeeper/cli.py", line 114, in train
    function(build_model, dataset, hparams, output_dir, **kwargs)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/larq_zoo/train.py", line 51, in train
    callbacks=callbacks,
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 724, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 681, in fit
    steps_name='steps_per_epoch')
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 298, in model_iteration
    batch_outs = f(actual_inputs)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3343, in __call__
    run_metadata=self.run_metadata)
  File "/home/yjm/anaconda2/envs/yjm_py3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1463, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 3 root error(s) found.
  (0) Invalid argument: {{function_node __inference_Dataset_map_<class 'functools.partial'>_181}} Invalid JPEG data, size 107746
	 [[{{node distorted_bounding_box_crop/ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[replica_3/metrics/top_k_categorical_accuracy/AssignAddVariableOp_1/_1718]]
  (1) Invalid argument: {{function_node __inference_Dataset_map_<class 'functools.partial'>_181}} Invalid JPEG data, size 107746
	 [[{{node distorted_bounding_box_crop/ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
  (2) Invalid argument: {{function_node __inference_Dataset_map_<class 'functools.partial'>_181}} Invalid JPEG data, size 107746
	 [[{{node distorted_bounding_box_crop/ExtractJpegShape}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[replica_3/training/SGD/gradients/gradients/replica_3/global_average_pooling2d/Mean_grad/Fill/_1639]]
0 successful operations.
2 derived errors ignored.

**Comment by lgeiger** [comment]
This looks like you are using  Larq Zoo version 0.3.0. To make sure, which version of `zookeeper` are you using.

This might be a problem with TensorFlow 2.0.0b1 which is still in early development. Are you seeing the same error with TensorFlow 1.14.1?

**Comment by lgeiger** [comment]
It looks like ImageNet version 2.0.1 includes some `.png` images which are not correctly converted: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/imagenet.py#L171-L179

Could you try running the command with `--dataset-version 5.0.0`? This is also what we used to train the models.

**Comment by appleleaves** [comment]
By saying TensorFlow 1.14.1, do you mean 1.14.0rc1?

**Comment by lgeiger** [comment]
Sorry, I meant 1.14.0
