### ISSUE TITLE
inference is not working

### ISSUE THREAD

**Issue by godhj93** [larq/larq#784]
### Describe the bug

Hi, my model has been trained to estimate depth information from rgb input. the model has auto-encoder structure and only encoder's weights and activation is binarized and decoder is full-precision.

after training, I called the model by using lce_benchmark_model --graph=my_bnn.tflite on AGX Xavier but it said 
```
hj@xavier:~/depth_estimator$ ./lce_benchmark_model --graph=BNN_encoder.tflite 
STARTING!
Log parameter values verbosely: [0]
Graph: [BNN_encoder.tflite]
Loaded model BNN_encoder.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
The input model file size (MB): 4.62667
Initialized session in 6.793ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
Segmentation fault (core dumped)
```

But when I save only encoder(not coupled with decoder) and call it again, inference works well.
```
./lce_benchmark_model --graph=BNN_sample.tflite --num_threads=4
STARTING!
Log parameter values verbosely: [0]
Num threads: [4]
Graph: [BNN_sample.tflite]
#threads used for CPU inference: [4]
Loaded model BNN_sample.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
The input model file size (MB): 4.61742
Initialized session in 11.641ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=8 first=95751 curr=60949 min=55821 max=95751 avg=65515.4 std=12320

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=50 first=54901 curr=53606 min=53291 max=70891 avg=56283.1 std=3423

Inference timings in us: Init: 11641, First inference: 95751, Warmup (avg): 65515.4, Inference (avg): 56283.1
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=10.8594 overall=96.3828

```
please let me know how to fix this issue.

### To Reproduce

I attached the models(tflite and tensorflow model) to reproduce the errors.
[Download Link](https://unistackr0-my.sharepoint.com/:f:/g/personal/godhj_unist_ac_kr/EhjQwyslXghJtRuLrFZUsTwBnAdycTKmEhrAh-V-60gkhg?e=XYp3IK)

BNN_sample.tflite is that only encoder has been converted by tensorflow lite and bnn_depth.tflite is full auto-encoder model.
you can check that the bnn_sample.tflite works well on xavier but bnn_depth.tflite not. 
and I also attached tensorflow keras model to produce tensorflow lite model so that the encoder model can be extracted by using 
```
encoder=model.layers[0]
```

### Expected behavior

I think when the mixture of BNN and Full-precision network, it makes the problem.
### Environment

TensorFlow version: 2.8.0
Larq version: 0.12.2

**Comment by CNugteren** [comment]
I ran your model locally on my x86 laptop and was able to reproduce the issue as well. I ran with and without XNNPack but that didn't change anything. I then re-ran it with a debug-version of the `lce_benchmark_model` and got this trace:
```c++
#2  0x00007ffff7a49729 in __assert_fail_base (fmt=0x7ffff7bdf588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555558f618 "this->rows()>0 && this->cols()>0 && \"you are using an empty matrix\"", file=0x555555573488 "external/eigen_archive/Eigen/src/Core/Redux.h", line=413, 
    function=<optimized out>) at assert.c:92
#3  0x00007ffff7a5afd6 in __GI___assert_fail (assertion=assertion@entry=0x55555558f618 "this->rows()>0 && this->cols()>0 && \"you are using an empty matrix\"", file=file@entry=0x555555573488 "external/eigen_archive/Eigen/src/Core/Redux.h", line=line@entry=413, 
    function=function@entry=0x555555587bb0 "typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_min_op<float, float, 0>; Derived = Eigen::Matrix<float, -1, 1>;"...) at assert.c:101
#4  0x0000555555783d90 in Eigen::DenseBase<Eigen::Matrix<float, -1, 1, 0, -1, 1> >::redux<Eigen::internal::scalar_min_op<float, float, 0> > (func=..., this=<synthetic pointer>) at external/eigen_archive/Eigen/src/Core/Redux.h:279
#5  Eigen::DenseBase<Eigen::Matrix<float, -1, 1, 0, -1, 1> >::minCoeff<0> (this=<synthetic pointer>) at external/eigen_archive/Eigen/src/Core/Redux.h:435
#6  Eigen::DenseBase<Eigen::Matrix<float, -1, 1, 0, -1, 1> >::minCoeff (this=<synthetic pointer>) at external/eigen_archive/Eigen/src/Core/DenseBase.h:453
#7  tflite::optimized_ops::AveragePool (params=..., input_shape=..., input_data=input_data@entry=0x555555a2bcc0, output_shape=..., output_data=output_data@entry=0x0) at external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/optimized_ops.h:3233
#8  0x0000555555783f3f in tflite::ops::builtin::pooling::AverageEvalFloat<(tflite::ops::builtin::pooling::KernelType)1> (context=context@entry=0x555555a30ee8, node=node@entry=0x555555a470d0, params=params@entry=0x555555a27c50, data=data@entry=0x555555a36090, 
    input=input@entry=0x555555a5fe40, output=<optimized out>) at external/org_tensorflow/tensorflow/lite/kernels/internal/runtime_shape.h:123
#9  0x0000555555784bc7 in tflite::ops::builtin::pooling::AverageEval<(tflite::ops::builtin::pooling::KernelType)1> (context=0x555555a30ee8, node=0x555555a470d0) at external/org_tensorflow/tensorflow/lite/kernels/internal/optimized/integer_ops/pooling.h:260
#10 0x00005555559b8472 in tflite::Subgraph::OpInvoke (op_reg=..., node=0x555555a470d0, this=0x555555a30ec0) at external/org_tensorflow/tensorflow/lite/core/subgraph.h:481
#11 tflite::Subgraph::Invoke (this=0x555555a30ec0) at external/org_tensorflow/tensorflow/lite/core/subgraph.cc:1219
#12 0x00005555559bc57c in tflite::Interpreter::Invoke (this=0x555555a26570) at /usr/include/c++/9/bits/unique_ptr.h:360
#13 0x000055555561b2f3 in tflite::benchmark::BenchmarkModel::Run (this=this@entry=0x7fffffffc360, min_num_times=1, min_secs=min_secs@entry=0.5, max_secs=max_secs@entry=150, run_type=run_type@entry=tflite::benchmark::WARMUP, invoke_status=invoke_status@entry=0x7fffffffbe44)
    at external/org_tensorflow/tensorflow/lite/tools/benchmark/benchmark_model.cc:198
#14 0x000055555561c98a in tflite::benchmark::BenchmarkModel::Run (this=this@entry=0x7fffffffc360) at external/org_tensorflow/tensorflow/lite/tools/tool_params.h:52
#15 0x000055555561d39a in tflite::benchmark::BenchmarkModel::Run (this=this@entry=0x7fffffffc360) at external/org_tensorflow/tensorflow/lite/tools/benchmark/benchmark_model.cc:248
#16 0x0000555555602d05 in tflite::benchmark::LceBenchmarkTfLiteModel::Run (this=0x7fffffffc360, argc=<optimized out>, argv=<optimized out>) at larq_compute_engine/tflite/benchmark/lce_benchmark_tflite_model.cc:70
#17 0x0000555555601f06 in tflite::benchmark::Main (argc=4, argv=0x7fffffffdaa8) at larq_compute_engine/tflite/benchmark/lce_benchmark_main.cc:39
```

Therefore, I conclude that the issue is not related to Larq or the Larq Compute Engine, since the error seems to come from an average pool layer implemented inside TensorFlow Lite itself. I then looked at your model and saw some odd-looking layers: a 2x2 average pool on 1x1 input data. Perhaps that's causing the issue? In any case, I would suggest to look at the average pool layers.

And if you can't solve the issue that way, I propose to first build a non-BNN version of this model and if similar issues appear: open an issue on the TensorFlow (Lite) repository.

**Comment by godhj93** [comment]
Thanks, the problem is solved when i specified the input shape.
